version: "3.9"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - bulls-volume:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/database
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  bulls-volume:
